"""create the eight tables

Revision ID: 6de3e43d23ec
Revises: 
Create Date: 2026-09-02 15:57:00.714588
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '6de3e43d23ec'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('units',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unit_number', sa.String(length=32), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('tenant_name', sa.String(length=120), nullable=False),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('unit_number')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('manager', 'contractor', name='role'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('maintenance_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('priority', sa.Enum('low', 'medium', 'high', 'urgent', name='priority'), nullable=False),
    sa.Column('status', sa.Enum('reported', 'triaged', 'scheduled', 'resolved', name='request_status'), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_requests_priority', 'maintenance_requests', ['priority'], unique=False)
    op.create_index('ix_requests_resolved_at', 'maintenance_requests', ['resolved_at'], unique=False)
    op.create_index('ix_requests_status', 'maintenance_requests', ['status'], unique=False)
    op.create_index('ix_requests_unit', 'maintenance_requests', ['unit_id'], unique=False)
    op.create_table('rent_alert_dismissals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('period_month', sa.Date(), nullable=False),
    sa.Column('dismissed_by', sa.Integer(), nullable=False),
    sa.Column('dismissed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dismissed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('unit_id', 'period_month', name='uq_dismissal_unit_month')
    )
    op.create_table('rent_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('period_month', sa.Date(), nullable=False),
    sa.Column('recorded_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('amount > 0', name='ck_rent_payments_positive'),
    sa.ForeignKeyConstraint(['recorded_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_rent_payments_unit_month', 'rent_payments', ['unit_id', 'period_month'], unique=False)
    op.create_table('unit_rents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('monthly_rent', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('monthly_rent >= 0', name='ck_unit_rents_non_negative'),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('unit_id', 'effective_from', name='uq_unit_rents_unit_month')
    )
    op.create_table('request_assignments',
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('contractor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['contractor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['maintenance_requests.id'], ),
    sa.PrimaryKeyConstraint('request_id', 'contractor_id')
    )
    op.create_index('ix_assignments_contractor', 'request_assignments', ['contractor_id'], unique=False)
    op.create_table('request_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.Enum('created', 'status_changed', 'assigned', 'unassigned', 'note', name='event_type'), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('old_value', sa.String(length=120), nullable=True),
    sa.Column('new_value', sa.String(length=120), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['maintenance_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_events_request_created', 'request_events', ['request_id', 'created_at'], unique=False)
    op.create_index('ix_events_type_created', 'request_events', ['event_type', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_events_type_created', table_name='request_events')
    op.drop_index('ix_events_request_created', table_name='request_events')
    op.drop_table('request_events')
    op.drop_index('ix_assignments_contractor', table_name='request_assignments')
    op.drop_table('request_assignments')
    op.drop_table('unit_rents')
    op.drop_index('ix_rent_payments_unit_month', table_name='rent_payments')
    op.drop_table('rent_payments')
    op.drop_table('rent_alert_dismissals')
    op.drop_index('ix_requests_unit', table_name='maintenance_requests')
    op.drop_index('ix_requests_status', table_name='maintenance_requests')
    op.drop_index('ix_requests_resolved_at', table_name='maintenance_requests')
    op.drop_index('ix_requests_priority', table_name='maintenance_requests')
    op.drop_table('maintenance_requests')
    op.drop_table('users')
    op.drop_table('units')
    # ### end Alembic commands ###
